services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: developer
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: aws_academy
    ports:
      - 3306:3306
    networks:
      - mysqlgo-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  app:
    build: .
    image: go-app
    container_name: go-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 8081:8081
    networks:
      - mysqlgo-network
    
networks:
  mysqlgo-network:
    name: mysqlgo-network

volumes:
  mysql_data:
    external: true
    name: mysql_data
