apiVersion: v1
kind: Pod
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  containers:
    - name: go-app
      image: bwbayu/go-app:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8081
      env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql_db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql_db_port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql_db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password